version: "3"
services:
  react-native-android:
    build:
      context: .
      args:
        BASE_DIR: ${BASE_DIR}
    environment:
      APP_NAME: ${APP_NAME}
      BASE_DIR: ${BASE_DIR}
    privileged: true
    ports:
      - 8081:8081
    tty: true
    command: >
      bash -c "cd /home/react-native &&
      bash ./create-native-app.sh $BASE_DIR $APP_NAME"
    volumes:
      - ".:/home/react-native"

volumes:
  node_modules:
    driver: local