version: '3.8'

services:
  jenio-codedir-template-workflows:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - GITHUB_ACCESS_TOKEN=b1ca76660664468e1b70dd5dc15470896b9886eb
    volumes:
      - ~/Jenio-CodeDir-Template:/home/ubuntu/sys/Jenio-CodeDir-Template
    ports:
      - "3000:3000"
    environment:
      REPOS_DIR: /home/ubuntu/sys/Jenio-CodeDir-Template/
      CURRENT_WORKSPACE_ID: "test"
      CODEDIR_TEMPLATE_REPO: http://github.com/neur0base/Jenio-CodeDir-Template/
